-- View: accpac.vw_apven

-- DROP VIEW accpac.vw_apven;

CREATE OR REPLACE VIEW accpac.vw_apven
 AS
 WITH vendors AS (
         SELECT btrim(apven_1.vendorid::text) AS vendorid,
            max(apven_1.audtdate) AS audtdate
           FROM accpac.apven apven_1
          GROUP BY (btrim(apven_1.vendorid::text))
        )
 SELECT btrim(apven.vendorid::text) AS vendorid,
    apven.audtdate,
    apven.audttime,
    apven.audtuser,
    apven.audtorg,
    apven.shortname,
    apven.idgrp,
    apven.swactv,
    apven.dateinac,
    apven.datelastmn,
    apven.swhold,
    apven.datestart,
    apven.idppnt,
    apven.vendname,
    apven.textstre1,
    apven.textstre2,
    apven.textstre3,
    apven.textstre4,
    apven.namecity,
    apven.codestte,
    apven.codepstl,
    apven.codectry,
    apven.namectac,
    apven.textphon1,
    apven.textphon2,
    apven.primrmit,
    apven.idacctset,
    apven.curncode,
    apven.ratetype,
    apven.bankid,
    apven.prtsepchks,
    apven.distsetid,
    apven.distcode,
    apven.glaccnt,
    apven.termscode,
    apven.dupinvccd,
    apven.dupamtcode,
    apven.dupdatecd,
    apven.codetaxgrp,
    apven.taxclass1,
    apven.taxclass2,
    apven.taxclass3,
    apven.taxclass4,
    apven.taxclass5,
    apven.taxrptsw,
    apven.subjtowthh,
    apven.taxnbr,
    apven.taxidtype,
    apven.taxnote2sw,
    apven.clasid,
    apven.amtcrlimt,
    apven.amtbalduet,
    apven.amtbaldueh,
    apven.amtppdinvt,
    apven.amtppdinvh,
    apven.dtlastrval,
    apven.amtballarv,
    apven.cntopeninv,
    apven.cntppdinvc,
    apven.cntinvpaid,
    apven.daystopay,
    apven.dateinvchi,
    apven.datebalhi,
    apven.dateinvhil,
    apven.datebalhil,
    apven.datelastac,
    apven.datelastiv,
    apven.datelastcr,
    apven.datelastdr,
    apven.datelastpa,
    apven.datelastdi,
    apven.datelstadj,
    apven.idinvchi,
    apven.idinvchily,
    apven.amtinvhit,
    apven.amtbalhit,
    apven.amtwthtcur,
    apven.amtinvhilt,
    apven.amtbalhilt,
    apven.amtwthlytc,
    apven.amtlastivt,
    apven.amtlastcrt,
    apven.amtlastdrt,
    apven.amtlastpyt,
    apven.amtlastdit,
    apven.amtlastadt,
    apven.amtinvhih,
    apven.amtbalhih,
    apven.amtwthhcur,
    apven.amtinvhilh,
    apven.amtbalhilh,
    apven.amtwthlyhc,
    apven.amtlastivh,
    apven.amtlastcrh,
    apven.amtlastdrh,
    apven.amtlastpyh,
    apven.amtlastdih,
    apven.amtlastadh,
    apven.paymcode,
    apven.idtaxregi1,
    apven.idtaxregi2,
    apven.idtaxregi3,
    apven.idtaxregi4,
    apven.idtaxregi5,
    apven.swdistby,
    apven.codecheck,
    apven.avgdayspay,
    apven.avgpayment,
    apven.amtinvpdhc,
    apven.amtinvpdtc,
    apven.cntnbrchks,
    apven.swtxinc1,
    apven.swtxinc2,
    apven.swtxinc3,
    apven.swtxinc4,
    apven.swtxinc5,
    apven.email1,
    apven.email2,
    apven.website,
    apven.ctacphone,
    apven.ctacfax,
    apven.delmethod,
    apven.rtgpercent,
    apven.rtgdays,
    apven.rtgterms,
    apven.rtgamttc,
    apven.rtgamthc,
    apven."VALUES",
    apven.nextcuid,
    apven.legalname,
    apven.chk1099amt,
    apven.idcust,
    apven.brn
   FROM accpac.apven
     JOIN vendors v ON btrim(apven.vendorid::text) = v.vendorid AND apven.audtdate = v.audtdate;

ALTER TABLE accpac.vw_apven
    OWNER TO sanelem;

